Add guidance on header parameters
w3c/vc-jwt pull request #109
Opened 2023-06-16 21:21 UTC by OR13

2023-06-16 22:06 UTC, mprorock commented on index.html
> +When present, members of the header are understood in the context of
```suggestion
When present, members of the header are to be interpreted and processed according to 
```

2023-06-16 22:08 UTC, mprorock requested changes
Minor rephrase suggested to prevent confusion over the work context

2023-06-20 17:00 UTC, OR13 commented
@mprorock applied your suggestion, can you re-review?

2023-06-20 19:14 UTC, andresuribe87 approved these changes

2023-06-21 16:50 UTC, mprorock approved these changes

2023-06-23 19:25 UTC, merged