Initial VC-JWT Editorial Corrections
w3c/vc-jwt pull request #29
Opened 2022-09-16 23:43 UTC by selfissued

2022-09-21 21:28 UTC, brentzundel approved these changes

2022-09-22 02:49 UTC, TallTed requested changes
a bit of rephrasing to improve clarity

2022-09-22 02:49 UTC, TallTed commented on index.html
>          express
```suggestion
        JSON Web Token (JWT) [[!RFC7519]] is a widely-used means of
        expressing
```

2022-09-22 02:49 UTC, TallTed commented on index.html
> +            the same way as with a standard <a>credential</a> and are added to
```suggestion
            the same way as with a standard <a>credential</a>, and the encoded <a>properties</a> are then added to
```

2022-10-12 18:32 UTC, Sakurann approved these changes

2022-10-12 20:02 UTC, OR13 approved these changes

2022-10-13 01:37 UTC, TallTed commented on index.html
>          express
Is there a reason this requested change has not been applied?

2022-10-13 01:37 UTC, TallTed commented on index.html
> +            the same way as with a standard <a>credential</a> and are added to
Is there a reason this requested change has not been applied?

2022-10-13 12:55 UTC, OR13 requested changes
Please address the suggestions, by accepting them or providing an explanation for why you would not like to accept them.

2022-10-13 21:30 UTC, merged