FPWD
w3c/vc-jwt pull request #74
Opened 2023-04-14 23:39 UTC by OR13

Prepare FPWD

2023-04-14 23:40 UTC, OR13 commented on index.html
> -described in [[!XMLSCHEMA11-2]].
This was causing a respec warning.

2023-04-15 01:00 UTC, decentralgabe approved these changes
:shipit:

2023-04-15 04:17 UTC, selfissued approved these changes
LGTM

2023-04-15 09:49 UTC, iherman requested changes
Per [my mail on the list](https://lists.w3.org/Archives/Public/public-vc-wg/2023Apr/0026.html) the publication date of the 20th does not work. The date should be changed to the 25th or the 27th, depending on the WG resolution

2023-04-15 13:03 UTC, OR13 commented
<img width="1232" alt="Screen Shot 2023-04-15 at 8 00 49 AM" src="https://user-images.githubusercontent.com/8295856/232225458-e5b95daa-f654-4b63-9b8e-411741e695c9.png">
<img width="1985" alt="Screen Shot 2023-04-15 at 7 59 46 AM" src="https://user-images.githubusercontent.com/8295856/232225460-9e5768a8-21dc-4532-9106-99453f4ce158.png">

2023-04-15 13:09 UTC, OR13 commented
I have updated the publication date to the 27th per the request on the list.

2023-04-16 07:23 UTC, iherman reviewed
Thanks @OR13. B.t.w., there is no bug in the link checker: the three links are, indeed, missing at this moment, but they will fall in place as part of the publication process. Actually, the FPWD has already been published, so the second error is already moot.

The official request for publication has gone out: https://github.com/w3c/transitions/issues/500 and, as far as I am concerned, this PR can be merged for historical purposes.

2023-04-16 07:23 UTC, iherman approved these changes

2023-04-17 18:51 UTC, OR13 commented
@brentzundel @Sakurann can I merge this PR?

2023-04-17 20:07 UTC, brentzundel commented
I support merging based on Ivan's comment above.

2023-04-17 20:09 UTC, Sakurann commented
Please merge

2023-04-17 21:10 UTC, OR13 commented
I am merging at the direction of our chairs and our staff contact.

2023-04-17 21:10 UTC, merged