Add context integrity approach for VC-JWTs
w3c/vc-jwt pull request #90
Opened 2023-05-30 13:17 UTC by mprorock

With verifiable credentials, or any signed JSON-LD it is often a desirable property to know that the context you are working with is the same on both ends, or if there has been a change.  This PR adds an optional ability to provide the hash of contexts used at issuance time.

***
<a href="https://pr-preview.s3.amazonaws.com/mesur-io/vc-jwt/pull/90.html" title="Last updated on Jun 2, 2023, 7:03 PM UTC (2b724aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jwt/90/e3ecd2e...mesur-io:2b724aa.html" title="Last updated on Jun 2, 2023, 7:03 PM UTC (2b724aa)">Diff</a>

2023-05-30 13:40 UTC, andresuribe87 commented
What are the benefits of putting this in vc-jwt, as opposed to putting them in the VCDM?

2023-05-30 13:43 UTC, mprorock commented
> What are the benefits of putting this in vc-jwt, as opposed to putting them in the VCDM?

this absolutely could go in the core data model if it is desired there - at minimum, having this in VC-JWT to address the security considerations notes around contexts in JSON-LD etc will be required.

2023-05-30 14:08 UTC, andresuribe87 commented on index.html
> +      the URL to the context named <code>context</code>, a
Currently, there might be two elements within `contextIntegrity` with the same `context` value. Should there be guidance that only one may be present?

2023-05-30 14:09 UTC, andresuribe87 commented on index.html
> +      that indicates when the context was retrieved and hashed, the
Implementers may find this ambiguous, is it the time of retrieval, or the time at which the hash was computed? I would recommend that we clarify. 

Furthermore, perhaps we can clarify that "time of retrieval" should mean "date and time immediately after the context was retrieved"

2023-05-30 14:12 UTC, andresuribe87 commented on index.html
> +      Named Information Hash Algorithm Registry</a>.
I think it's valuable for us to choose or recommend which hashing algorithm implementers should use. I would say use sha-256 by default. We could also say that when not present, `sha-256` is assumed.

2023-05-30 14:13 UTC, andresuribe87 commented on index.html
> +        <p>An example of a context integrity object</p>
It would be great if we could add an example of the content that was hashed, so implementers know whether their implementations will be interoperable.

2023-05-30 15:16 UTC, mprorock commented
thanks @andresuribe87 - i added a few things based on your careful reading.  very very much appreciated.

2023-05-30 15:26 UTC, andresuribe87 approved these changes

2023-05-30 19:42 UTC, decentralgabe approved these changes

2023-06-01 14:50 UTC, selfissued requested changes
This is not at all JWT-like.  For instance, it uses a long-form timestamp rather than a numeric time value.

I also believe that, should we decide that we want this functionality, it belongs in the data model rather than VC-JWT, because that's where the context stuff is.  We shouldn't be doing anything to add to context semantics in this spec.

2023-06-01 15:53 UTC, mprorock commented
> This is not at all JWT-like. For instance, it uses a long-form timestamp rather than a numeric time value.
> 
> I also believe that, should we decide that we want this functionality, it belongs in the data model rather than VC-JWT, because that's where the context stuff is. We shouldn't be doing anything to add to context semantics in this spec.

I think the core data model is likely a better place for this.... Will want bring it up on the next VCWG call @Sakurann @brentzundel

2023-06-01 16:35 UTC, OR13 commented on index.html
> +      In some cases is is desireable to know that the contents of the
```suggestion
      In some cases it is desirable to know that the contents of the
```

2023-06-01 16:36 UTC, OR13 commented on index.html
> +      context(s) utilized in the verifiable credential is the same as
```suggestion
      context(s) utilized in the verifiable credential are the same as
```

2023-06-01 16:37 UTC, OR13 commented
> This is not at all JWT-like. For instance, it uses a long-form timestamp rather than a numeric time value.

This is because this is a core data model "extension" that just happens to be being defined here... which... seems wrong.

This should be handled like all the other "core data model extensions", in the core spec.

And I would object there a well, unless a similar bar to what has been met for `renderMethod` is achieved.

2023-06-01 16:38 UTC, OR13 requested changes
Core data model extension points belong in the core data model.

2023-06-02 19:12 UTC, mprorock commented
opened [this pr on core data model](https://github.com/w3c/vc-data-model/pull/1140) that would permit us to not handle this in vc-jwt as it is really across teh board an issue for VC securing formats and should be handled consistently

2023-06-06 17:03 UTC, TallTed requested changes
Tweaks for clarity

2023-06-06 17:03 UTC, TallTed commented on index.html
> +      context used when issuing the VC matches the remote resource.
```suggestion
      If subresource integrity as defined in [[SRI]] is adopted into
      the [[JSON-LD]] specification at a later date, as noted in the
      <a href="https://www.w3.org/TR/json-ld11/#security">current security
      considerations</a> of that specification, this hash in the VC can
      serve as an additional check towards ensuring that a cached
      context used when issuing the VC matches the remote resource.
```

2023-06-06 18:33 UTC, OR13 commented
This PR should be closed, because https://github.com/w3c/vc-data-model/pull/1140 has been opened.

2023-06-07 15:42 UTC, closed without merging