Add an explainer
w3c/vc-jwt pull request #96
Opened 2023-05-30 14:49 UTC by mprorock

obviously we will build on this and make it better

2023-06-01 17:09 UTC, mprorock commented on explainer.md
> +* Michael Jones
```suggestion
* Michael B. Jones
```

2023-06-01 17:10 UTC, mprorock commented on explainer.md
> +the data model. [JWTs](https://www.rfc-editor.org/rfc/rfc7519) provide a
```suggestion
Multiple different methods can be used to cryptographically secure 
content encoded using the Verifiable Credentials (VCs) data model. 
[JWTs](https://www.rfc-editor.org/rfc/rfc7519) provide a
```

2023-06-01 17:14 UTC, mprorock commented
@selfissued we are charted explicity for core data model - I am fine to expand the explainer later and have noted the valid concern raised here in #99 - can we get this approved and merged as is to be able to start horizontal review with tag per issue #97 ? 

we cannot do this until explainer is merged.

2023-06-01 17:51 UTC, OR13 approved these changes

2023-06-01 17:54 UTC, OR13 commented on explainer.md
> +the data model. [JWTs](https://www.rfc-editor.org/rfc/rfc7519) provide a
> Before we check this in, I believe we need to describe how VC-JWT payloads can use native JWT claims and need not use JSON-LD.

You are suggesting this PR needs to be merged or closed :https://github.com/w3c/vc-jwt/pull/88

Before we can add this explain and start our horizontal review?

I agree.

2023-06-06 16:16 UTC, TallTed requested changes
Minor tweaks and corrections for clarity

2023-06-07 02:35 UTC, selfissued approved these changes
At some point, I believe we need to describe how VC-JWT payloads can use native JWT claims and need not use JSON-LD.

2023-06-07 15:41 UTC, OR13 commented
Multiple approvals, changes requested and implemented, merging.

2023-06-07 15:41 UTC, merged

2023-06-07 20:34 UTC, TallTed commented
> [@selfissued] At some point, I believe we need to describe how VC-JWT payloads can use native JWT claims and need not use JSON-LD.

I suggest you create an Issue and/or PR for this.

2023-06-09 22:25 UTC, andresuribe87 commented
> > [@selfissued] At some point, I believe we need to describe how VC-JWT payloads can use native JWT claims and need not use JSON-LD.
> 
> I suggest you create an Issue and/or PR for this.

Perhaps we can use #98 to track